---
title: "Wöchentliche Vorbereitung auf die Seminar-Sitzung"
author: "Felix Dietrich"
categories:
  - "BA Inhaltsanalyse: Inhalte öffentlicher Kommunikation KF G"
  - "Wintersemester 2024/2025"
csl: "../bib/apa-cv.csl"
bibliography: "../bib/24-2-ia.bib"
suppress-bibliography: true
link-citations: false
---

## Leseaufgabe

Um sich auf die nächste Sitzung vorzubereiten, **lesen Sie bitte die folgenden Paper** (PDFs im LMS):

**Verpflichtende Lektüre:**

- @walterInitiationEvolutionPSRs2023
- @leithParasocialCuesUbiquity2021

Machen Sie sich während der Lektüre **Notizen zu den folgenden Fragen**. Sie sollten in der Lage sein, diese **Fragen in der Sitzung soweit es geht zu beantworten** und **mit Ihren Kommiliton:innen darüber zu diskutieren**. Aber: Die Texte sind nicht einfach zu verstehen. Es ist nicht schlimm, wenn Sie nicht alles direkt verstehen. Notieren Sie sich Fragen zu Aspekten, die Ihnen unklar geblieben sind.

- Wie entstehen PSBs?
- Was sind potentielle Prädiktoren für die Intensität von PSBs?
- Was meint Leith mit "verbal immediacy"? Notieren Sie sich Fragen zu möglichen Unklarheiten
- Was sind potentielle Unterschiede bei PSI und PSB zu Social-Media-Persönlichkeiten im Vergleich zu TV-Personae (z.B. Charactere in einem Film oder Nachrichtensprecher:innen)
- Überlegen Sie sich, inwiefern das alles auf das Anwendungsbeispiel der Family-Vlogs zutreffen kann

**Ergänzende Literatur:**

- @bondDevelopmentInfluenceParasocial2021
- @fahrEntertainmentJourneyNot2021
- @hartmannHortonWohlRevisited2011
- @hortonMassCommunicationParasocial1956
- @kurtinDevelopmentParasocialInteraction2018
- @rubinLonelinessParasocialInteraction1985
- @tukachinskyTheorizingDevelopmentParasocial2019